### ISSUE TITLE
Tag doesn't parse.

### ISSUE THREAD

**Issue by eagsalazar** [creeperyang/id3-parser#12]
I did some debugging and seems like this tag doesn't parse for a couple issues:

1. Length of the buffer after the header is computed to be way too short [(in parseV2FromBuffer)](https://github.com/creeperyang/id3-parser/blob/master/lib/parser.js#L165)
2. Length of slice, after initial slice is always 0 so all frames are skipped [(in calcFrameSize)](https://github.com/creeperyang/id3-parser/blob/master/lib/parser.js#L335)

I am passing a Uint8Array:
```
ID3.parse(samples[0].unit).then(tag => {
     console.log(tag)
})
```

Specifically this is the data I get out of hls.js on timed metadata events on `Hls.Events.FRAG_PARSING_METADATA`.

Here is the Uint8Array for testing:

```
test = [73,68,51,4,0,0,0,0,0,63,80,82,73,86,0,0,0,53,0,0,99,111,109,46,97,112,112,108,101,46,115,116,114,101,97,109,105,110,103,46,116,114,97,110,115,112,111,114,116,83,116,114,101,97,109,84,105,109,101,115,116,97,109,112,0,0,0,0,0,191,178,114,97,73,68,51,4,0,0,0,0,3,84,84,82,83,78,0,0,0,27,0,0,3,83,116,114,101,97,109,83,32,83,116,114,101,97,109,105,110,103,32,69,110,99,111,100,101,114,0,84,82,83,79,0,0,0,23,0,0,3,72,105,45,70,105,32,73,110,116,101,114,110,101,116,32,83,116,114,101,97,109,0,84,73,84,50,0,0,0,30,0,0,3,77,101,97,110,44,32,71,114,101,101,110,44,32,75,105,108,108,105,110,103,32,77,97,99,104,105,110,101,0,84,80,69,49,0,0,0,10,0,0,3,79,118,101,114,107,105,108,108,0,87,88,88,88,0,0,0,38,0,0,3,97,114,116,119,111,114,107,85,82,76,95,54,52,48,120,0,104,116,116,112,58,47,47,103,105,109,109,101,114,97,100,105,111,46,99,111,109,84,70,76,84,0,0,0,9,0,0,3,77,80,71,47,65,65,67,0,84,88,88,88,0,0,0,51,0,0,3,99,114,98,0,83,116,114,101,97,109,83,32,76,105,118,101,32,72,84,84,80,32,69,110,99,111,100,101,114,32,83,101,114,118,105,99,101,32,40,118,32,49,46,50,46,50,46,57,52,41,84,88,88,88,0,0,0,51,0,0,3,101,110,99,0,83,116,114,101,97,109,83,32,76,105,118,101,32,72,84,84,80,32,69,110,99,111,100,101,114,32,83,101,114,118,105,99,101,32,40,118,32,49,46,50,46,50,46,57,52,41,84,88,88,88,0,0,0,33,0,0,3,100,101,118,0,76,105,110,101,32,50,32,40,86,105,114,116,117,97,108,32,65,117,100,105,111,32,67,97,98,108,101,41,84,88,88,88,0,0,0,6,0,0,3,97,111,116,0,50,84,88,88,88,0,0,0,8,0,0,3,97,100,114,0,50,53,54,84,88,88,88,0,0,0,10,0,0,3,97,115,114,0,52,56,48,48,48,84,88,88,88,0,0,0,6,0,0,3,97,99,104,0,50,84,88,88,88,0,0,0,26,0,0,3,99,114,100,0,50,48,49,55,48,50,48,52,32,50,51,58,51,50,58,53,51,32,85,84,67]
```

If you convert to a string you can see it has the v2 tags in it:
```
unit = new Uint8Array(test)
tagAsString = new TextDecoder('utf-8').decode(unit)
```

Roughly:

> "ID3?PRIV5com.apple.streaming.transportStreamTimestamp��raID3TTRSNStreamS Streaming EncoderTRSOHi-Fi Internet StreamTIT2Mean, Green, Killing MachineTPE1
> OverkillWXXX&artworkURL_640xhttp://foobar.comTFLT	MPG/AACTXXX3crbStreamS Live HTTP Encoder Service (v 1.2.2.94)TXXX3encStreamS Live HTTP Encoder Service (v 1.2.2.94)TXXX!devLine 2 (Virtual Audio Cable)TXXXaot2TXXXadr256TXXX
> asr48000TXXXach2TXXXcrd20170204 23:32:53 UTC"

I realize all this might be because the minor id3v2 version is 4 and 2.4 does not appear to be supported yet.  Is that correct?  If so can you recommend another approach or outline what is needed to support 2.4 and maybe I'll try to implement it?

**Comment by creeperyang** [comment]
Good investigation, and you're right, `ID3 v2.4` is **not** supported.

Pr to support version 4 is welcome.

**Comment by eagsalazar** [comment]
I'm not an expert in this topic and would honestly love to find something off the shelf.   If you can give me specific guidance I can give it a shot though!   Otherwise, do you have suggestions for alternative js libraries?

id3-parser is unique in that it operates directly on the id3 tag where most other id3 libs are coupled tightly, in their api and implementation, to reading an entire mp3 or other media file, extracting the id3 from it, then parsing.

**Comment by creeperyang** [comment]
`ID3 v2.4` frames are different from `v2.3`. See <http://id3.org/id3v2.4.0-structure> and <http://id3.org/id3v2.4.0-frames>.

I have no idea which js lib has supported it.
