### ISSUE TITLE
File with no id3 tags returning input instead of emitting error

### ISSUE THREAD

**Issue by dvdcxn** [creeperyang/id3-parser#13]
When parsing a file with no actual ID3 tag info, I noticed that this simply results in the buffer fed into the function being returned. Presumably this is the case with other types of input.

I was wondering if it would be sensible for this to throw an error, or make such behaviour configurable. It would make handling this exceptional behaviour within the promise chain a little cleaner, especially when dealing with mapped files.

See below code for an example of how this would behave in practice - presumably if the version object is false, then the stats failed, thus i throw an error inside the handler.

```javascript
function analyseFile(fileName) {
	let _readFile = bluebird.promisify(readFile);
	return _readFile(fileName)
		.then(id3.parse)
		.then(stats => {	
			if(stats.version){	
				return stats;
			}
			else{
				throw `Couldn\'t determine id3 data for file ${fileName}`;
			}		
		})
		.catch(console.error);
}

function analyseFiles(globs) {
	let _glob = bluebird.promisify(glob);
	return _glob(globs)
		.map(analyseFile);
}
```

**Comment by creeperyang** [comment]
@dvdcxn I think there is no need to change `id3-parser`'s behavior.

You could wrap the lib yourself, such as code below:

```js
function analyseFile(fileName) {
	let _readFile = bluebird.promisify(readFile);
        let content;
	return _readFile(fileName)
                .then(buf => {
                       content = buf;
                       return buf;
                 })
		.then(id3.parse)
		.then(stats => {	
			if(stats.version){	
				return stats;
			}
			else{
				throw `Couldn\'t determine id3 data for file ${fileName}`;
			}		
		})
		.catch(err => {
                    return content;
                });
}
```

**Comment by dvdcxn** [comment]
@creeperyang  Will do. Is checking whether the version is truthy a reliable enough way to determine whether the id3 parse worked?

**Comment by creeperyang** [comment]
No. If the buffer's length is less than required, `false` is returned.

```js
if (stats && stats.version) {}
```

Good question! I should make the promise rejected when the buffer is less than expected.

**Comment by creeperyang** [comment]
@dvdcxn `v1.2` has fixed this, and you can always check `stats.version` to determine whether the id3 parse worked.

- If invalid argument passed, the promise rejected.
- If the buffer is not valid `id3v1` or `id3v2` buffer, you get `{version: false}`.
- Otherwise, you get

    ```js
    {
       version: {
          v1: false | object,
          v2: false | object
       }
    }
    ```

Enjoy the new version.
