### ISSUE TITLE
Memory gobbled when using a buffer as input

### ISSUE THREAD

**Issue by azariah001** [creeperyang/id3-parser#4]
For some reason when parsing file buffers directly into the id3 parser the memory doesn't get released, ever. Well until the script is killed and even then. It's a known issue with buffers because they're actually points to C++ memory locations containing the actual buffer. So setting a buffer to null or attempting to overwrite it only results in you loosing access to the original buffer it doesn't release the memory.

So the solution! Which I'll be updating in the readme, don't parse buffers directly into the id3 parser.

````
id3.parse(new Uint8Array(buffer)).then(function(tags) {

});
````

Still takes a while for the garbage collection to clean up the buffers but.... they do get cleaned up. I just went from using ~400Mb of RAM for my test file set down to 91Mb (on server I've gone from 600-700Mb of memory used to 140Mb) so I'm fairly happy now but... if the parser is going to support raw buffers as input we need to make sure it is dereferencing them properly.

I presume the issue could be solved if the buffer input were immediately converted into a Unit8Array just as I'm doing outside the script but... I'm obviously not certain of that at this point. I'll look into it once my semester is done in a couple of weeks.

**Comment by creeperyang** [comment]
I'm not very clear about your issue. I tested memory leak with `memwatch` and found no leak.

```shell
stats: {"num_full_gc":1,"num_inc_gc":3,"heap_compactions":1,"usage_trend":0,"estimated_base":8547360,"current_base":8547360,"min":0,"max":0}
mem: { rss: 157667328, heapTotal: 138165760, heapUsed: 115051040 }
stats: {"num_full_gc":2,"num_inc_gc":8,"heap_compactions":2,"usage_trend":0,"estimated_base":40045416,"current_base":40045416,"min":0,"max":0}
mem: { rss: 157954048, heapTotal: 138165760, heapUsed: 115452648 }
```

So any more description? It's nice if you show your test code.

**Comment by RedSparr0w** [comment]
@azariah001 Thanks, your fix seemed to work for me. memory was freed up in about 10 seconds after reading the files.

example below (reading 111 files 950Mb)
_note: i am using this within electron_

before reading files: ~100Mb
after reading files: ~1000Mb
after reading files + ~10 seconds: ~100Mb
```javascript
id3.parse(new Uint8Array(fs.readFileSync(file.path))).then(tags => {
  console.info(tags);
});
```
### -VS-
before reading files: ~100Mb
after reading files: ~950Mb
after reading files + ~10 minutes: ~950Mb
```javascript
id3.parse(fs.readFileSync(file.path)).then(tags => {
  console.info(tags);
});
```
