### ISSUE TITLE
Type Definition File

### ISSUE THREAD

**Issue by dvdcxn** [creeperyang/id3-parser#7]
First off - this is by far the most simple and effective id3 parser I've found for node, thank you!

I've created a typing for this for use with typescript. It is also registered within the typings registry so it can be pulled into projects as a dependency.

You can find it here - https://github.com/dvdcxn/typed-id3-parser

I'm not sure how familiar you are with typescript but I reckon folk will find it useful. Would it be worth updating the readme with information on how to install it?

**Comment by creeperyang** [comment]
Thanks. 

I'm not familiar with `typescript`, So a pr for `readme` is welcome. You can describe installation info about `typed-id3-parser` and more.
